export const AppSettings = {
  "SCORE_FACTOR": 0.75,
  "ATTACK_FACTOR": 0.75,
  "FAULT_FACTOR": 0.01,
  "AGE_EFFECT": 0.5,
  "TIME_EFFECT": 0.1,
  "SUPPORTERS_EFFECT": 0.01,
  "FORM_EFFECT": 0.1,
  "PLAYING_STYLE_EFFECT": 0.2,
  "MINIMAL_FORM": 75,
  "REFEREE_PERSONALITY_FACTOR": 0.02,
  "REFEREE_RED_CARD": 0.1,
  "RED_CARD_EFFECT": 50
}